- name: Deploy VM from content library OVF.
  vmware.vmware.deploy_content_library_ovf:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    library: "{{ content_library }}"
    item: "{{ template_name }}"
    name: "{{ vm_name }}"
    placement:
      cluster: "{{ cluster }}"
      folder: "{{ folder }}"
      datastore: "{{ datastore }}"
    power_on: false
