- name: Apply tags to VM
  community.vmware.vmware_tag_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    object_name: "{{ vm_name }}"
    object_type: "VirtualMachine"
    tags: "{{ tagging }}"
